/**
 * Researches current security/AI news via the Claude API's web search tool and
 * drafts an article in the site's house style. Called by the generate-articles
 * cron route; never publishes — everything lands as a draft for human review.
 */
import Anthropic from "@anthropic-ai/sdk";
import { getPayload } from "payload";
import { Resend } from "resend";
import config from "@payload-config";
import type { Article } from "@/payload-types";
import { categories, siteConfig } from "@/site.config";

/**
 * Cover images are picked from this verified pool rather than generated by the
 * model — a hallucinated image URL renders as a broken image on the live site,
 * and the model has no way to check that a URL resolves.
 */
const COVER_IMAGES: Record<string, string[]> = {
  security: [
    "https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=1600&q=80",
    "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=1600&q=80",
    "https://images.unsplash.com/photo-1544890225-2f3faec4cd60?w=1600&q=80",
    "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1600&q=80",
    "https://images.unsplash.com/photo-1523437113738-bbd3cc89fb19?w=1600&q=80",
  ],
  ai: [
    "https://images.unsplash.com/photo-1633265486064-086b219458ec?w=1600&q=80",
    "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=1600&q=80",
    "https://images.unsplash.com/photo-1782918843144-920ff238efc5?w=1600&q=80",
    "https://images.unsplash.com/photo-1591696205602-2f950c417cb9?w=1600&q=80",
  ],
  startups: [
    "https://images.unsplash.com/photo-1560264280-88b68371db39?w=1600&q=80",
    "https://images.unsplash.com/photo-1680992046626-418f7e910589?w=1600&q=80",
  ],
  gadgets: ["https://images.unsplash.com/photo-1518770660439-4636190af475?w=1600&q=80"],
  world: ["https://images.unsplash.com/photo-1539796326180-5d8272550830?w=1600&q=80"],
};

const ARTICLE_SCHEMA = {
  type: "object",
  properties: {
    found_story: {
      type: "boolean",
      description:
        "True only if a real, current story was verified via web search this session. False if searches failed, were rate-limited, or surfaced nothing recent — in which case leave every other field empty.",
    },
    title: {
      type: "string",
      description:
        "Headline. States what actually changed. No colons-as-subtitle clickbait, no 'Here's why'.",
    },
    slug: {
      type: "string",
      description: "URL slug: lowercase, hyphen-separated, 3-8 words, no dates.",
    },
    excerpt: {
      type: "string",
      description: "1-2 sentences. The specific finding, not a teaser.",
    },
    body: {
      type: "string",
      description:
        "Markdown body, ~600 words. Opens with what changed. Uses ## subheads, and lists/tables/blockquotes where they earn their place.",
    },
    categorySlug: {
      type: "string",
      enum: categories.map((c) => c.slug),
    },
    tags: {
      type: "array",
      items: { type: "string" },
      description: "2-4 lowercase kebab-case topic tags.",
    },
    readingMinutes: { type: "integer" },
    sources: {
      type: "array",
      items: { type: "string" },
      description: "URLs actually consulted via web search. Used for review, not published.",
    },
  },
  required: [
    "found_story",
    "title",
    "slug",
    "excerpt",
    "body",
    "categorySlug",
    "tags",
    "readingMinutes",
    "sources",
  ],
  additionalProperties: false,
} as const;

const SYSTEM_PROMPT = `You write for Root Notes, a security and infrastructure news blog.

Voice and format:
- ~600 words. Every post is capped at a five-minute read.
- Open with what actually changed. Explain why it matters before what happened.
- Explainer-first: a reader who skims the first paragraph should get the point.
- Use ## subheads. Use lists, tables, and blockquotes only where they carry information prose wouldn't.
- Direct and specific. No hype, no "in today's fast-paced landscape", no rhetorical questions as subheads.
- End with what the reader should actually do or watch, not a summary.

Accuracy is the hard constraint:
- Only write about events you found and verified via web search in this session.
- Never invent an incident, CVE, company, breach, number, or date. If your search didn't surface a specific figure, don't state one.
- Prefer stories with at least two independent sources. Attribute contested claims.

If you cannot verify a story — searches fail, are rate-limited, or surface nothing recent enough — set found_story to false and leave the other fields empty. Do NOT write about the fact that you couldn't find a story: that is not an article, and it will be discarded. Returning found_story false is a correct, expected outcome, not a failure.

Beats, in priority order: trending cyber attacks, new data breaches, AI innovation and new models, hacking tools and security products.`;

export type GeneratedArticle = {
  found_story: boolean;
  title: string;
  slug: string;
  excerpt: string;
  body: string;
  categorySlug: string;
  tags: string[];
  readingMinutes: number;
  sources: string[];
};

function pickCoverImage(categorySlug: string, seed: number): string {
  const pool = COVER_IMAGES[categorySlug] ?? COVER_IMAGES.security;
  return pool[seed % pool.length];
}

/**
 * True when web search produced nothing usable — every attempt errored.
 *
 * Search errors arrive as HTTP 200 with an error object in place of the results
 * array, so they never raise and have to be checked for explicitly. Crucially,
 * a *partial* failure is normal and must not abort the run: the model reliably
 * attempts one search past `max_uses` and gets `max_uses_exceeded` back, which
 * is our own budget working as intended, not a fault. An earlier version failed
 * the run on any error and threw away good articles because of that last call.
 */
function searchFullyFailed(message: Anthropic.Message): string | null {
  let succeeded = 0;
  let firstError: string | null = null;

  for (const block of message.content) {
    if (block.type !== "web_search_tool_result") continue;

    if (Array.isArray(block.content)) {
      if (block.content.length > 0) succeeded += 1;
    } else if (!firstError) {
      firstError = block.content.error_code ?? "unknown";
    }
  }

  return succeeded === 0 ? (firstError ?? "no results") : null;
}

/** Pulls the URLs the web_search tool actually returned, deduped, newest first. */
function searchedUrls(message: Anthropic.Message): string[] {
  const urls = new Set<string>();

  for (const block of message.content) {
    if (block.type !== "web_search_tool_result") continue;
    // `content` is a result array on success and a single error object on
    // failure (e.g. max_uses_exceeded) — guard before iterating.
    if (!Array.isArray(block.content)) continue;

    for (const result of block.content) {
      if (result.url) urls.add(result.url);
    }
  }

  return [...urls].slice(0, 8);
}

type CategorySlug = Article["categorySlug"];

/** Narrows a model-supplied category string to the collection's enum, or null. */
function existingCategory(slug: string): CategorySlug | null {
  const match = categories.find((c) => c.slug === slug);
  return match ? (match.slug as CategorySlug) : null;
}

/**
 * Researches and drafts one article. Returns null if nothing publishable was
 * found — which is a normal outcome, not an error.
 *
 * Retries on transport failures because a run holds a streaming connection open
 * for minutes and ECONNRESET mid-stream was observed twice in testing. The
 * SDK's own retries don't cover a drop after the stream has started, and this
 * runs unattended on a schedule, so an un-retried drop is a silently missed
 * article.
 */
export async function generateArticle(
  existingTitles: string[],
): Promise<GeneratedArticle | null> {
  const MAX_ATTEMPTS = 3;

  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    try {
      return await attemptGeneration(existingTitles);
    } catch (err) {
      const isLast = attempt === MAX_ATTEMPTS;
      const reason = err instanceof Error ? err.message : String(err);
      console.warn(`[generator] attempt ${attempt}/${MAX_ATTEMPTS} failed: ${reason}`);
      if (isLast) throw err;
      await new Promise((r) => setTimeout(r, attempt * 5000));
    }
  }

  return null;
}

async function attemptGeneration(
  existingTitles: string[],
): Promise<GeneratedArticle | null> {
  const client = new Anthropic();

  const avoid = existingTitles.length
    ? `\n\nWe have already covered these — pick a different story:\n${existingTitles
        .map((t) => `- ${t}`)
        .join("\n")}`
    : "";

  const stream = client.messages.stream({
    // Sonnet rather than Opus: news research and ~600-word summarisation is
    // well within Sonnet's range, and web-search results make the input large
    // enough that the per-article price difference is roughly 3x.
    model: "claude-sonnet-5",
    max_tokens: 16000,
    system: SYSTEM_PROMPT,
    thinking: { type: "adaptive" },
    output_config: {
      effort: "medium",
      format: { type: "json_schema", schema: ARTICLE_SCHEMA },
    },
    // Search results dominate the bill — a measured 8-search run pulled 209K
    // input tokens (~$0.45 of a ~$0.59 article). 4 is enough to corroborate a
    // story across sources; raising it raises cost roughly proportionally.
    tools: [{ type: "web_search_20260209", name: "web_search", max_uses: 4 }],
    messages: [
      {
        role: "user",
        content: `Search the web for a significant, recent story on one of our beats — a cyber attack, a data breach, an AI model or capability release, or a notable security tool. Prioritise the last 48 hours.

Verify the details across sources, then write the article.${avoid}`,
      },
    ],
  });

  const message = await stream.finalMessage();

  if (message.stop_reason === "refusal") {
    console.warn("[generator] request refused:", message.stop_details);
    return null;
  }

  const text = message.content.find((b) => b.type === "text");
  if (!text || text.type !== "text") {
    console.warn("[generator] no text block in response; stop_reason:", message.stop_reason);
    return null;
  }

  // When search returns nothing at all, the model has no material — and left to
  // itself it will write *about* that. One observed run produced "Search Limit
  // Reached Before a New Story Could Be Verified" as a full article. Bail
  // before parsing rather than let that reach the drafts queue.
  const searchError = searchFullyFailed(message);
  if (searchError) {
    console.warn(`[generator] web search returned nothing (${searchError}) — skipping this run`);
    return null;
  }

  try {
    const parsed = JSON.parse(text.text) as GeneratedArticle;

    // A schema-valid response is not necessarily a usable one. Two observed
    // failure modes: `title: "placeholder"` with a one-word body, and a
    // meta-article about being unable to search. found_story is the model's
    // own signal; the word count catches stubs it still marks as found.
    if (!parsed.found_story) {
      console.log("[generator] model reported no verifiable story this run");
      return null;
    }

    const wordCount = parsed.body.trim().split(/\s+/).length;
    if (wordCount < 200) {
      console.warn(`[generator] body too short (${wordCount} words) — discarding`);
      return null;
    }
    // Take sources from the search results the API actually returned rather
    // than the model's self-reported list — the model reliably leaves that
    // field empty, and the tool results are ground truth for what it read.
    const searched = searchedUrls(message);
    if (!searched.length) {
      console.warn("[generator] no web searches performed — discarding");
      return null;
    }

    return { ...parsed, sources: searched };
  } catch (err) {
    console.error("[generator] could not parse model output as JSON:", err);
    return null;
  }
}

/** Researches, drafts, and saves one article as a draft. Returns the slug, or null. */
export async function generateAndSaveDraft(): Promise<string | null> {
  const payload = await getPayload({ config });

  const { docs: existing } = await payload.find({
    collection: "articles",
    limit: 40,
    sort: "-publishedAt",
    depth: 0,
  });

  const article = await generateArticle(existing.map((d) => d.title));
  if (!article) return null;

  // The schema constrains categorySlug to the valid enum, but the value still
  // arrives as a plain string — re-check it here rather than casting, so a
  // malformed response fails loudly instead of writing a bad row.
  const category = existingCategory(article.categorySlug);
  if (!category) {
    console.error(`[generator] unknown categorySlug: ${article.categorySlug}`);
    return null;
  }

  // The model picks its own slug, so a collision with an existing article is
  // possible even though it was told what we've covered — suffix rather than
  // fail, since the draft is reviewed by a human before it goes live anyway.
  let slug = article.slug;
  const taken = new Set(existing.map((d) => d.slug));
  if (taken.has(slug)) slug = `${slug}-2`;

  const created = await payload.create({
    collection: "articles",
    data: {
      title: article.title,
      slug,
      excerpt: article.excerpt,
      body: article.body,
      categorySlug: category,
      tags: article.tags,
      author: "Prince Baruwala",
      publishedAt: new Date().toISOString(),
      readingMinutes: article.readingMinutes,
      status: "draft",
      featured: false,
      views: 0,
      coverImageUrl: pickCoverImage(article.categorySlug, existing.length),
    },
  });

  console.log(`[generator] drafted: ${slug} (sources: ${article.sources.join(", ")})`);
  await notifyAdmin(article, slug, created.id);
  return slug;
}

/**
 * Emails the admin that a draft is waiting for review. Deliberately never
 * throws: the draft is already saved by this point, and a notification failure
 * should not turn a successful generation run into a 500.
 */
async function notifyAdmin(
  article: GeneratedArticle,
  slug: string,
  id: number | string,
): Promise<void> {
  const apiKey = process.env.RESEND_API_KEY;
  const to = process.env.ADMIN_EMAIL;

  if (!apiKey || !to) {
    console.warn(
      `[generator] RESEND_API_KEY or ADMIN_EMAIL not set — no notification sent for ${slug}`,
    );
    return;
  }

  const editUrl = `${siteConfig.url}/admin/collections/articles/${id}`;
  const sourcesHtml = article.sources
    .map((s) => `<li><a href="${s}">${s}</a></li>`)
    .join("");

  try {
    const resend = new Resend(apiKey);
    await resend.emails.send({
      from: process.env.RESEND_FROM_EMAIL ?? "onboarding@resend.dev",
      to,
      subject: `Draft ready for review: ${article.title}`,
      html: `<div style="font-family:sans-serif;max-width:600px;margin:0 auto">
        <p style="color:#888;font-size:13px;margin:0">New ${siteConfig.name} draft — not published yet</p>
        <h2 style="margin:6px 0 4px">${article.title}</h2>
        <p style="color:#444;line-height:1.5">${article.excerpt}</p>
        <p style="color:#888;font-size:13px">${article.categorySlug} · ${article.readingMinutes} min read</p>
        <p style="margin:24px 0">
          <a href="${editUrl}" style="background:#111;color:#fff;padding:10px 18px;border-radius:6px;text-decoration:none">Review &amp; publish</a>
        </p>
        <p style="color:#888;font-size:12px;margin-bottom:4px">Sources the model used — worth spot-checking before publishing:</p>
        <ul style="color:#888;font-size:12px;line-height:1.6">${sourcesHtml}</ul>
      </div>`,
    });
    console.log(`[generator] notified ${to} about ${slug}`);
  } catch (err) {
    console.error("[generator] notification failed (draft was still saved):", err);
  }
}
